module.exports = [
  "eres un adefesio",
  "eres un alcornoque",
  "eres una bazofia",
  "~ baboso",
  "eres tonto o le tiras piedras a los aviones",
  "eres más infantil que una pelea entre Pokemones y Power Rangers",
  "tienes menos futuro que un enfermo de parkinson tocando pandero",
  "eres tan feo que cuando naciste tintaron los cristales de la incubadora",
  "si los tontos tuvieran hélice tu serías un helicóptero",
  "que mala suerte que de 5 millones de espermatozoides salieras tú...",
  "cómprate un desierto y bárrelo",
  "dime cómo te llamas para poder poner nombre a mis pesadillas",
  "parece que tus viejos no le pusieron mucho empeño pa' hacerte",
  "Creo que eres un trasero",
  "No eres más larg@ de cabeza a pies que de cadera a cadera, eres esféric@ como un globo en el que podría encontrar países.",
  "Me arrepiento de los tediosos minutos que he pasado contigo.",
  "Tu rostro es como el invierno, lleno de escarcha, tormentas y nubosidad.",
  "Eres un Lame pies.",
  "Tú eres el indice y el prologo de la historia de la lujuria y falta de pensamiento.",
  "Mienten terriblemente los que dicen que tienes buen aspecto.",
  "¡Fuera! Eres veneno para mi sangre.",
  "chant aún peoén lat ula",
  "erís más feo que la azafata del Caleuche",
  "erís más feo que la mentira",
  "erís más falso que billete de 1500",
  "erís más ordinario que linchaco de longaniza",
  "erís más inútil que bolsillo de pijama"
]
